// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251206212548_ProblemStatusValueObjectMigration")]
    partial class ProblemStatusValueObjectMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryProblem", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("categories_id");

                    b.Property<Guid>("ProblemsId")
                        .HasColumnType("uuid")
                        .HasColumnName("problems_id");

                    b.HasKey("CategoriesId", "ProblemsId")
                        .HasName("pk_fk_problem_categories");

                    b.HasIndex("ProblemsId")
                        .HasDatabaseName("ix_fk_problem_categories_problems_id");

                    b.ToTable("fk_problem_categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000101"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000301")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000102"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000302")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000104"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000303")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000103"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000304")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000108"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000304")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000107"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000305")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000108"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000305")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000101"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000306")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000107"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000306")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000101"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000307")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000109"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000308")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000103"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000309")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000107"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000309")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000106"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-00000000030a")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000107"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-00000000030a")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000105"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-00000000030b")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000103"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-00000000030c")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000108"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-00000000030c")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000106"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-00000000030d")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000107"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-00000000030d")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000104"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-00000000030e")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000103"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-00000000030f")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000104"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000310")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000106"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000310")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000101"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000311")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000108"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000312")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000107"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000312")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000105"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000313")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000103"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000314")
                        },
                        new
                        {
                            CategoriesId = new Guid("00000000-0000-0000-0000-000000000107"),
                            ProblemsId = new Guid("00000000-0000-0000-0000-000000000314")
                        });
                });

            modelBuilder.Entity("Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000101"),
                            Name = "Дороги та тротуари"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000102"),
                            Name = "Освітлення"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000103"),
                            Name = "Благоустрій"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000104"),
                            Name = "Сміття та екологія"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000105"),
                            Name = "Комунальні послуги"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000106"),
                            Name = "Транспорт"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000107"),
                            Name = "Безпека"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000108"),
                            Name = "Парки та зелені зони"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000109"),
                            Name = "Будівництво"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000010a"),
                            Name = "Інше"
                        });
                });

            modelBuilder.Entity("Domain.Comments.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(300)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_comments_problem_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comments_user_id");

                    b.ToTable("comments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000401"),
                            Content = "Так, підтверджую. Їздив сьогодні, ледь не зламав підвіску.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProblemId = new Guid("00000000-0000-0000-0000-000000000301"),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000402"),
                            Content = "Вже місяць як така ситуація. Коли вже відремонтують?",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProblemId = new Guid("00000000-0000-0000-0000-000000000301"),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000403"),
                            Content = "Дуже небезпечно ходити ввечері, треба терміново виправити.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProblemId = new Guid("00000000-0000-0000-0000-000000000302"),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000404"),
                            Content = "Жахлива ситуація, смердить на всю вулицю.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProblemId = new Guid("00000000-0000-0000-0000-000000000303"),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000405"),
                            Content = "Дякую, що виправили!",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProblemId = new Guid("00000000-0000-0000-0000-000000000304"),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000406"),
                            Content = "Дійсно небезпечно, особливо при сильному вітрі.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProblemId = new Guid("00000000-0000-0000-0000-000000000305"),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000407"),
                            Content = "Діти щодня переходять дорогу, це дуже небезпечно!",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProblemId = new Guid("00000000-0000-0000-0000-000000000306"),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000408"),
                            Content = "Коли почнуть ремонт? Діти не можуть нормально гратися.",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProblemId = new Guid("00000000-0000-0000-0000-000000000309"),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000409"),
                            Content = "Вода вже затопила половину дороги!",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProblemId = new Guid("00000000-0000-0000-0000-00000000030b"),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000040a"),
                            Content = "Це екологічна катастрофа для нашого міста!",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProblemId = new Guid("00000000-0000-0000-0000-00000000030e"),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        });
                });

            modelBuilder.Entity("Domain.Identity.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "User"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Coordinator"
                        });
                });

            modelBuilder.Entity("Domain.Identity.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Email = "admin@ostroh.edu.ua",
                            FullName = "Адміністратор Острога",
                            PasswordHash = "31jGqnyNWeEpqqSOGrrFYA==:pt36JXYoIE3w8xtI8rEJU/h50muKgFwRs0p/h4am3A0="
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Email = "user@ostroh.edu.ua",
                            FullName = "Звичайний Користувач",
                            PasswordHash = "OeuuWFIVglEfvDvcH349ow==:OXOk32vZFxUcodlJVPaLj/qOApIGP9SSVu9RBy+O4Sc="
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Email = "coordinator@ostroh.edu.ua",
                            FullName = "Координатор Острога",
                            PasswordHash = "DXIF+E53jMJS34YZkf0Jkw==:ccAPZCJbWy/stpuqDGYoAeNnHM5rABefB+bMZL+EaZY="
                        });
                });

            modelBuilder.Entity("Domain.Identity.Users.UserImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_image");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_image_user_id");

                    b.ToTable("user_image", (string)null);
                });

            modelBuilder.Entity("Domain.Problems.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoordinatorComment")
                        .HasColumnType("text")
                        .HasColumnName("coordinator_comment");

                    b.Property<Guid?>("CoordinatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("coordinator_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("CurrentState")
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("current_state");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserConfirmationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("user_confirmation_status");

                    b.HasKey("Id")
                        .HasName("pk_problems");

                    b.HasIndex("CoordinatorId")
                        .HasDatabaseName("ix_problems_coordinator_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_problems_created_by_id");

                    b.ToTable("problems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000301"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Велика яма на дорозі біля будинку №15. Потрібує термінового ремонту.",
                            Latitude = 50.3294,
                            Longitude = 26.514399999999998,
                            Status = "Нова",
                            Title = "Розбита дорога на вул. Академічна",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserConfirmationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000302"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Вже тиждень не світять ліхтарі на ділянці від будинку №10 до №20.",
                            Latitude = 50.328499999999998,
                            Longitude = 26.512499999999999,
                            Status = "В роботі",
                            Title = "Не працює вуличне освітлення на вул. Семінарська",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserConfirmationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000303"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Сміттєві контейнери не вивозяться вже 3 дні, сміття розкидане навколо.",
                            Latitude = 50.330100000000002,
                            Longitude = 26.5167,
                            Status = "Нова",
                            Title = "Переповнені сміттєві баки біля ринку",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserConfirmationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000304"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Дерев'яна лавка зламана, потребує заміни або ремонту.",
                            Latitude = 50.327800000000003,
                            Longitude = 26.518899999999999,
                            Status = "Виконано",
                            Title = "Зламана лавка в парку Тараса Шевченка",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserConfirmationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000305"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Старе дерево нахилилося і може впасти на дорогу. Небезпечно для пішоходів та транспорту.",
                            Latitude = 50.331200000000003,
                            Longitude = 26.509799999999998,
                            Status = "В роботі",
                            Title = "Аварійне дерево на вул. Луцька",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserConfirmationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000306"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Пішохідний перехід біля школи №2 без розмітки, небезпечно для дітей.",
                            Latitude = 50.328899999999997,
                            Longitude = 26.515599999999999,
                            Status = "Нова",
                            Title = "Відсутня розмітка на пішохідному переході",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserConfirmationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000307"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Великі тріщини на тротуарі, небезпечно для пішоходів, особливо в темний час доби.",
                            Latitude = 50.330500000000001,
                            Longitude = 26.513400000000001,
                            Status = "Нова",
                            Title = "Тріщина на тротуарі вул. Папаніна",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserConfirmationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000308"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Ведеться будівництво без відповідних дозволів, порушується архітектурний вигляд міста.",
                            Latitude = 50.329799999999999,
                            Longitude = 26.517800000000001,
                            Status = "Відхилено",
                            Title = "Незаконне будівництво на вул. Князів Острозьких",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserConfirmationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000309"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Гойдалки та гірка на дитячому майданчику в аварійному стані.",
                            Latitude = 50.328200000000002,
                            Longitude = 26.514199999999999,
                            Status = "В роботі",
                            Title = "Потребує ремонту дитячий майданчик",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserConfirmationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000030a"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "На перехресті вул. Академічна та вул. Семінарська відсутній знак пріоритету.",
                            Latitude = 50.3307,
                            Longitude = 26.516100000000002,
                            Status = "Нова",
                            Title = "Відсутній дорожній знак на перехресті",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserConfirmationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000030b"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Витік води з водопровідної труби, вода заливає дорогу.",
                            Latitude = 50.329099999999997,
                            Longitude = 26.517099999999999,
                            Status = "В роботі",
                            Title = "Прорив водопроводу на вул. Замкова",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserConfirmationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000030c"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Клумби біля центральної площі не доглядаються, заросли бур'яном.",
                            Latitude = 50.329599999999999,
                            Longitude = 26.514900000000001,
                            Status = "Нова",
                            Title = "Зарослі бур'яном клумби в центрі",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserConfirmationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000030d"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Світлофор на перехресті не працює вже другий день.",
                            Latitude = 50.331499999999998,
                            Longitude = 26.510200000000001,
                            Status = "В роботі",
                            Title = "Не працює світлофор на вул. Луцька",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserConfirmationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000030e"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Стихійне сміттєзвалище утворилося в лісосмузі за містом.",
                            Latitude = 50.327199999999998,
                            Longitude = 26.519500000000001,
                            Status = "Нова",
                            Title = "Сміттєзвалище в лісосмузі",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserConfirmationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000030f"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Огорожа школи №1 іржава та потребує фарбування.",
                            Latitude = 50.328800000000001,
                            Longitude = 26.5138,
                            Status = "Виконано",
                            Title = "Потребує фарбування огорожа школи",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserConfirmationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000310"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "На автобусній зупинці 'Центр' немає урн для сміття.",
                            Latitude = 50.330199999999998,
                            Longitude = 26.5153,
                            Status = "Нова",
                            Title = "Відсутні урни на зупинці",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserConfirmationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000311"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Бордюр зруйнований на протяжності 5 метрів.",
                            Latitude = 50.329900000000002,
                            Longitude = 26.516400000000001,
                            Status = "Нова",
                            Title = "Зламаний бордюр на вул. Князів Острозьких",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserConfirmationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000312"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Гілки дерева загрожують електричним проводам.",
                            Latitude = 50.328600000000002,
                            Longitude = 26.514700000000001,
                            Status = "В роботі",
                            Title = "Потребує обрізки дерева біля будинку",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserConfirmationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000313"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Після дощу утворюються великі калюжі через відсутність каналізації.",
                            Latitude = 50.3279,
                            Longitude = 26.513200000000001,
                            Status = "Нова",
                            Title = "Відсутня каналізація на вул. Садова",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserConfirmationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000314"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Вандали розмалювали фасад історичної будівлі в центрі міста.",
                            Latitude = 50.329300000000003,
                            Longitude = 26.517499999999998,
                            Status = "Виконано",
                            Title = "Граффіті на фасаді історичної будівлі",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserConfirmationStatus = 0
                        });
                });

            modelBuilder.Entity("Domain.Problems.ProblemImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id")
                        .HasName("pk_problem_image");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_problem_image_problem_id");

                    b.ToTable("problem_image", (string)null);
                });

            modelBuilder.Entity("Domain.Ratings.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<double>("Points")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("points");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ratings");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_ratings_problem_id");

                    b.HasIndex("UserId", "ProblemId")
                        .IsUnique()
                        .HasDatabaseName("ix_ratings_user_id_problem_id");

                    b.ToTable("ratings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Rating_Points_Range", "points >= 1.00 AND points <= 5.00");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000501"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Points = 4.5,
                            ProblemId = new Guid("00000000-0000-0000-0000-000000000301"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000502"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Points = 5.0,
                            ProblemId = new Guid("00000000-0000-0000-0000-000000000302"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000503"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Points = 4.7999999999999998,
                            ProblemId = new Guid("00000000-0000-0000-0000-000000000303"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000504"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Points = 5.0,
                            ProblemId = new Guid("00000000-0000-0000-0000-000000000305"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000505"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Points = 4.9000000000000004,
                            ProblemId = new Guid("00000000-0000-0000-0000-000000000306"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000506"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Points = 4.2000000000000002,
                            ProblemId = new Guid("00000000-0000-0000-0000-000000000307"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000507"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Points = 4.7000000000000002,
                            ProblemId = new Guid("00000000-0000-0000-0000-00000000030a"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000508"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Points = 5.0,
                            ProblemId = new Guid("00000000-0000-0000-0000-00000000030b"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000509"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Points = 4.5999999999999996,
                            ProblemId = new Guid("00000000-0000-0000-0000-00000000030e"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000050a"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Points = 4.2999999999999998,
                            ProblemId = new Guid("00000000-0000-0000-0000-000000000311"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        });
                });

            modelBuilder.Entity("Domain.RefreshTokens.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<DateTime>("ExpiredDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_date")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("jwt_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid")
                        .HasColumnName("roles_id");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid")
                        .HasColumnName("users_id");

                    b.HasKey("RolesId", "UsersId")
                        .HasName("pk_fk_user_roles");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_fk_user_roles_users_id");

                    b.ToTable("fk_user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            RolesId = new Guid("00000000-0000-0000-0000-000000000001"),
                            UsersId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            RolesId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UsersId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            RolesId = new Guid("00000000-0000-0000-0000-000000000003"),
                            UsersId = new Guid("00000000-0000-0000-0000-000000000012")
                        });
                });

            modelBuilder.Entity("CategoryProblem", b =>
                {
                    b.HasOne("Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fk_problem_categories_categories_categories_id");

                    b.HasOne("Domain.Problems.Problem", null)
                        .WithMany()
                        .HasForeignKey("ProblemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fk_problem_categories_problems_problems_id");
                });

            modelBuilder.Entity("Domain.Comments.Comment", b =>
                {
                    b.HasOne("Domain.Problems.Problem", "Problem")
                        .WithMany("Comments")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_problems_problem_id");

                    b.HasOne("Domain.Identity.Users.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_user_id");

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Identity.Users.UserImage", b =>
                {
                    b.HasOne("Domain.Identity.Users.User", "User")
                        .WithOne("UserImage")
                        .HasForeignKey("Domain.Identity.Users.UserImage", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_images_users_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Problems.Problem", b =>
                {
                    b.HasOne("Domain.Identity.Users.User", "Coordinator")
                        .WithMany()
                        .HasForeignKey("CoordinatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_problems_users_coordinator_id");

                    b.HasOne("Domain.Identity.Users.User", "CreatedBy")
                        .WithMany("Problems")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_problems_users_created_by_id");

                    b.Navigation("Coordinator");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Domain.Problems.ProblemImage", b =>
                {
                    b.HasOne("Domain.Problems.Problem", "Problem")
                        .WithMany("Images")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_images_id");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("Domain.Ratings.Rating", b =>
                {
                    b.HasOne("Domain.Problems.Problem", "Problem")
                        .WithMany("Ratings")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ratings_problems_problem_id");

                    b.HasOne("Domain.Identity.Users.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ratings_users_user_id");

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.RefreshTokens.RefreshToken", b =>
                {
                    b.HasOne("Domain.Identity.Users.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Domain.Identity.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fk_user_roles_roles_roles_id");

                    b.HasOne("Domain.Identity.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fk_user_roles_users_users_id");
                });

            modelBuilder.Entity("Domain.Identity.Users.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Problems");

                    b.Navigation("Ratings");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserImage");
                });

            modelBuilder.Entity("Domain.Problems.Problem", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Images");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
