// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260210204251_ChangedSeededDataIDs")]
    partial class ChangedSeededDataIDs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Comments.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(300)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_comments_problem_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comments_user_id");

                    b.ToTable("comments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d"),
                            Content = "Підтверджую, яма дуже глибока, пошкодив колесо.",
                            CreatedAt = new DateTime(2024, 1, 16, 15, 0, 0, 0, DateTimeKind.Utc),
                            ProblemId = new Guid("6a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            UpdatedAt = new DateTime(2024, 1, 16, 15, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d")
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e"),
                            Content = "Дякуємо за звернення, передали в дорожню службу.",
                            CreatedAt = new DateTime(2024, 1, 16, 16, 0, 0, 0, DateTimeKind.Utc),
                            ProblemId = new Guid("6a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            UpdatedAt = new DateTime(2024, 1, 16, 16, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("7d0c1b2a-3e4f-5a6b-7c8d-9e0f1a2b3c4d")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f"),
                            Content = "Темно ввечері ходити, небезпечно.",
                            CreatedAt = new DateTime(2024, 1, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            ProblemId = new Guid("5b2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"),
                            UpdatedAt = new DateTime(2024, 1, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d")
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a"),
                            Content = "Жахливий запах, неможливо пройти повз.",
                            CreatedAt = new DateTime(2024, 1, 16, 18, 0, 0, 0, DateTimeKind.Utc),
                            ProblemId = new Guid("4c3d4e5f-6a7b-8c9d-0e1f-2a3b4c5d6e7f"),
                            UpdatedAt = new DateTime(2024, 1, 16, 18, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1e2f-3a4b-5c6d7e8f9a0b"),
                            Content = "Прошу терміново вирішити, гілки вже торкаються проводів.",
                            CreatedAt = new DateTime(2024, 1, 16, 19, 0, 0, 0, DateTimeKind.Utc),
                            ProblemId = new Guid("3d4e5f6a-7b8c-9d0e-1f2a-3b4c5d6e7f8a"),
                            UpdatedAt = new DateTime(2024, 1, 16, 19, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d")
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-2f3a-4b5c-6d7e8f9a0b1c"),
                            Content = "Діти переходять дорогу в небезпечному місці.",
                            CreatedAt = new DateTime(2024, 1, 16, 20, 0, 0, 0, DateTimeKind.Utc),
                            ProblemId = new Guid("2e5f6a7b-8c9d-0e1f-2a3b-4c5d6e7f8a9b"),
                            UpdatedAt = new DateTime(2024, 1, 16, 20, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d")
                        },
                        new
                        {
                            Id = new Guid("12345678-9abc-def0-1234-56789abcdef0"),
                            Content = "Вода тече вже третій день, ніхто не реагує.",
                            CreatedAt = new DateTime(2024, 1, 16, 21, 0, 0, 0, DateTimeKind.Utc),
                            ProblemId = new Guid("9b8c9d0e-1f2a-3b4c-5d6e-7f8a9b0c1d2e"),
                            UpdatedAt = new DateTime(2024, 1, 16, 21, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d")
                        });
                });

            modelBuilder.Entity("Domain.Identity.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("34a92614-7d43-41c6-9430-891a92543265"),
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("97897262-63fe-45f8-b7eb-661bf11f0c23"),
                            Name = "User"
                        },
                        new
                        {
                            Id = new Guid("42ad2488-8250-4286-921c-4395e1e19409"),
                            Name = "Coordinator"
                        });
                });

            modelBuilder.Entity("Domain.Identity.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClerkId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("clerk_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Surname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("ClerkId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_clerk_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f2b8c3d-4a5e-6f7a-8b9c-0d1e2f3a4b5c"),
                            ClerkId = "user_38GDF8VSzp5vQGWOBgk0Kv3Td7W",
                            Email = "admin@ostroh.edu.ua",
                            Name = "Адміністратор",
                            PasswordHash = "31jGqnyNWeEpqqSOGrrFYA==:pt36JXYoIE3w8xtI8rEJU/h50muKgFwRs0p/h4am3A0=",
                            RoleId = new Guid("34a92614-7d43-41c6-9430-891a92543265"),
                            Surname = "Острога"
                        },
                        new
                        {
                            Id = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d"),
                            ClerkId = "user_38GDs4xMAfETf7thv21MwyW72bh",
                            Email = "user@ostroh.edu.ua",
                            Name = "Звичайний",
                            PasswordHash = "OeuuWFIVglEfvDvcH349ow==:OXOk32vZFxUcodlJVPaLj/qOApIGP9SSVu9RBy+O4Sc=",
                            RoleId = new Guid("97897262-63fe-45f8-b7eb-661bf11f0c23"),
                            Surname = "Користувач"
                        },
                        new
                        {
                            Id = new Guid("7d0c1b2a-3e4f-5a6b-7c8d-9e0f1a2b3c4d"),
                            ClerkId = "user_38GDlYzZ1LZNY3q4uFLBMyAYp4Y",
                            Email = "coordinator@ostroh.edu.ua",
                            Name = "Координатор",
                            PasswordHash = "DXIF+E53jMJS34YZkf0Jkw==:ccAPZCJbWy/stpuqDGYoAeNnHM5rABefB+bMZL+EaZY=",
                            RoleId = new Guid("42ad2488-8250-4286-921c-4395e1e19409"),
                            Surname = "Острога"
                        });
                });

            modelBuilder.Entity("Domain.Identity.Users.UserImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_image");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_image_user_id");

                    b.ToTable("user_image", (string)null);
                });

            modelBuilder.Entity("Domain.Problems.CoordinatorImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id")
                        .HasName("pk_coordinator_image");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_coordinator_image_problem_id");

                    b.ToTable("coordinator_image", (string)null);
                });

            modelBuilder.Entity("Domain.Problems.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("categories");

                    b.Property<string>("CoordinatorComment")
                        .HasColumnType("text")
                        .HasColumnName("coordinator_comment");

                    b.Property<Guid?>("CoordinatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("coordinator_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("CurrentState")
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("current_state");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("priority");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_problems");

                    b.HasIndex("CoordinatorId")
                        .HasDatabaseName("ix_problems_coordinator_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_problems_created_by_id");

                    b.ToTable("problems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            Categories = "[\"\\u0414\\u043E\\u0440\\u043E\\u0433\\u0438\"]",
                            CreatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d"),
                            Description = "Велика яма на дорозі біля будинку №15. Потребує термінового ремонту.",
                            Latitude = 50.3294,
                            Longitude = 26.514399999999998,
                            Priority = "Високий",
                            Status = "Нова",
                            Title = "Розбита дорога на вул. Академічна",
                            UpdatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5b2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"),
                            Categories = "[\"\\u041E\\u0441\\u0432\\u0456\\u0442\\u043B\\u0435\\u043D\\u043D\\u044F\"]",
                            CreatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d"),
                            Description = "Вже тиждень не світять ліхтарі на ділянці від будинку №5 до №15.",
                            Latitude = 50.328499999999998,
                            Longitude = 26.512499999999999,
                            Priority = "Середній",
                            Status = "Нова",
                            Title = "Не працює вуличне освітлення на вул. Семінарська",
                            UpdatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("4c3d4e5f-6a7b-8c9d-0e1f-2a3b4c5d6e7f"),
                            Categories = "[\"\\u0421\\u043C\\u0456\\u0442\\u0442\\u044F\"]",
                            CreatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d"),
                            Description = "Сміттєві контейнери не вивозяться вже 3 дні, сміття розкидане навколо.",
                            Latitude = 50.330100000000002,
                            Longitude = 26.5167,
                            Priority = "Високий",
                            Status = "Нова",
                            Title = "Переповнені сміттєві баки біля ринку",
                            UpdatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3d4e5f6a-7b8c-9d0e-1f2a-3b4c5d6e7f8a"),
                            Categories = "[\"\\u0411\\u0435\\u0437\\u043F\\u0435\\u043A\\u0430\",\"\\u041F\\u0430\\u0440\\u043A\\u0438 \\u0442\\u0430 \\u0437\\u0435\\u043B\\u0435\\u043D\\u0456 \\u0437\\u043E\\u043D\\u0438\"]",
                            CreatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d"),
                            Description = "Старе дерево нахилилося і може впасти на дорогу. Небезпечно для пішоходів.",
                            Latitude = 50.331200000000003,
                            Longitude = 26.509799999999998,
                            Priority = "Критичний",
                            Status = "В роботі",
                            Title = "Аварійне дерево на вул. Луцька",
                            UpdatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2e5f6a7b-8c9d-0e1f-2a3b-4c5d6e7f8a9b"),
                            Categories = "[\"\\u0414\\u043E\\u0440\\u043E\\u0433\\u0438\",\"\\u0411\\u0435\\u0437\\u043F\\u0435\\u043A\\u0430\"]",
                            CreatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d"),
                            Description = "Пішохідний перехід біля школи №2 без розмітки, небезпечно для дітей.",
                            Latitude = 50.328899999999997,
                            Longitude = 26.515599999999999,
                            Priority = "Високий",
                            Status = "В роботі",
                            Title = "Відсутня розмітка на пішохідному переході",
                            UpdatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("1f6a7b8c-9d0e-1f2a-3b4c-5d6e7f8a9b0c"),
                            Categories = "[\"\\u0414\\u043E\\u0440\\u043E\\u0433\\u0438\"]",
                            CreatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d"),
                            Description = "Великі тріщини на тротуарі, небезпечно для пішоходів та велосипедистів.",
                            Latitude = 50.330500000000001,
                            Longitude = 26.513400000000001,
                            Priority = "Середній",
                            Status = "Нова",
                            Title = "Тріщина на тротуарі вул. Папаніна",
                            UpdatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("0a7b8c9d-0e1f-2a3b-4c5d-6e7f8a9b0c1d"),
                            Categories = "[\"\\u0411\\u0435\\u0437\\u043F\\u0435\\u043A\\u0430\",\"\\u041F\\u0430\\u0440\\u043A\\u0438 \\u0442\\u0430 \\u0437\\u0435\\u043B\\u0435\\u043D\\u0456 \\u0437\\u043E\\u043D\\u0438\"]",
                            CreatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d"),
                            Description = "Гойдалки та гірка на дитячому майданчику в аварійному стані.",
                            Latitude = 50.328200000000002,
                            Longitude = 26.514199999999999,
                            Priority = "Високий",
                            Status = "В роботі",
                            Title = "Потребує ремонту дитячий майданчик",
                            UpdatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9b8c9d0e-1f2a-3b4c-5d6e-7f8a9b0c1d2e"),
                            Categories = "[\"\\u0412\\u043E\\u0434\\u043E\\u043F\\u043E\\u0441\\u0442\\u0430\\u0447\\u0430\\u043D\\u043D\\u044F\"]",
                            CreatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d"),
                            Description = "Витік води з водопровідної труби, вода заливає дорогу.",
                            Latitude = 50.329099999999997,
                            Longitude = 26.517099999999999,
                            Priority = "Критичний",
                            Status = "Нова",
                            Title = "Прорив водопроводу на вул. Замкова",
                            UpdatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8c9d0e1f-2a3b-4c5d-6e7f-8a9b0c1d2e3f"),
                            Categories = "[\"\\u041F\\u0430\\u0440\\u043A\\u0438 \\u0442\\u0430 \\u0437\\u0435\\u043B\\u0435\\u043D\\u0456 \\u0437\\u043E\\u043D\\u0438\"]",
                            CreatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d"),
                            Description = "Клумби біля центральної площі не доглядаються, заросли бур'яном.",
                            Latitude = 50.329599999999999,
                            Longitude = 26.514900000000001,
                            Priority = "Низький",
                            Status = "Нова",
                            Title = "Зарослі бур'яном клумби в центрі",
                            UpdatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7d0e1f2a-3b4c-5d6e-7f8a-9b0c1d2e3f4a"),
                            Categories = "[\"\\u0411\\u0435\\u0437\\u043F\\u0435\\u043A\\u0430\",\"\\u0414\\u043E\\u0440\\u043E\\u0433\\u0438\"]",
                            CreatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d"),
                            Description = "Світлофор на перехресті не працює вже другий день, створює аварійну ситуацію.",
                            Latitude = 50.331499999999998,
                            Longitude = 26.510200000000001,
                            Priority = "Критичний",
                            Status = "Відхилено",
                            Title = "Не працює світлофор на вул. Луцька",
                            UpdatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Domain.Problems.ProblemImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id")
                        .HasName("pk_problem_image");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_problem_image_problem_id");

                    b.ToTable("problem_image", (string)null);
                });

            modelBuilder.Entity("Domain.Ratings.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<double>("Points")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("points");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ratings");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_ratings_problem_id");

                    b.HasIndex("UserId", "ProblemId")
                        .IsUnique()
                        .HasDatabaseName("ix_ratings_user_id_problem_id");

                    b.ToTable("ratings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Rating_Points_Range", "points >= 1.00 AND points <= 5.00");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("ace3e57e-07c8-4767-9610-639556214582"),
                            CreatedAt = new DateTime(2024, 1, 17, 11, 0, 0, 0, DateTimeKind.Utc),
                            Points = 5.0,
                            ProblemId = new Guid("6a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            UserId = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d")
                        },
                        new
                        {
                            Id = new Guid("bde3e57e-07c8-4767-9610-639556214583"),
                            CreatedAt = new DateTime(2024, 1, 17, 12, 0, 0, 0, DateTimeKind.Utc),
                            Points = 4.0,
                            ProblemId = new Guid("6a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d"),
                            UserId = new Guid("9f2b8c3d-4a5e-6f7a-8b9c-0d1e2f3a4b5c")
                        },
                        new
                        {
                            Id = new Guid("cde3e57e-07c8-4767-9610-639556214584"),
                            CreatedAt = new DateTime(2024, 1, 17, 13, 0, 0, 0, DateTimeKind.Utc),
                            Points = 4.0,
                            ProblemId = new Guid("5b2c3d4e-5f6a-7b8c-9d0e-1f2a3b4c5d6e"),
                            UserId = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d")
                        },
                        new
                        {
                            Id = new Guid("dde3e57e-07c8-4767-9610-639556214585"),
                            CreatedAt = new DateTime(2024, 1, 17, 14, 0, 0, 0, DateTimeKind.Utc),
                            Points = 5.0,
                            ProblemId = new Guid("4c3d4e5f-6a7b-8c9d-0e1f-2a3b4c5d6e7f"),
                            UserId = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d")
                        },
                        new
                        {
                            Id = new Guid("ede3e57e-07c8-4767-9610-639556214586"),
                            CreatedAt = new DateTime(2024, 1, 17, 15, 0, 0, 0, DateTimeKind.Utc),
                            Points = 5.0,
                            ProblemId = new Guid("3d4e5f6a-7b8c-9d0e-1f2a-3b4c5d6e7f8a"),
                            UserId = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d")
                        },
                        new
                        {
                            Id = new Guid("fde3e57e-07c8-4767-9610-639556214587"),
                            CreatedAt = new DateTime(2024, 1, 17, 16, 0, 0, 0, DateTimeKind.Utc),
                            Points = 4.0,
                            ProblemId = new Guid("2e5f6a7b-8c9d-0e1f-2a3b-4c5d6e7f8a9b"),
                            UserId = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d")
                        },
                        new
                        {
                            Id = new Guid("00e3e57e-07c8-4767-9610-639556214588"),
                            CreatedAt = new DateTime(2024, 1, 17, 17, 0, 0, 0, DateTimeKind.Utc),
                            Points = 3.0,
                            ProblemId = new Guid("1f6a7b8c-9d0e-1f2a-3b4c-5d6e7f8a9b0c"),
                            UserId = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d")
                        },
                        new
                        {
                            Id = new Guid("11e3e57e-07c8-4767-9610-639556214589"),
                            CreatedAt = new DateTime(2024, 1, 17, 18, 0, 0, 0, DateTimeKind.Utc),
                            Points = 5.0,
                            ProblemId = new Guid("9b8c9d0e-1f2a-3b4c-5d6e-7f8a9b0c1d2e"),
                            UserId = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d")
                        },
                        new
                        {
                            Id = new Guid("22e3e57e-07c8-4767-9610-639556214590"),
                            CreatedAt = new DateTime(2024, 1, 17, 19, 0, 0, 0, DateTimeKind.Utc),
                            Points = 5.0,
                            ProblemId = new Guid("7d0e1f2a-3b4c-5d6e-7f8a-9b0c1d2e3f4a"),
                            UserId = new Guid("8e1a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5d")
                        });
                });

            modelBuilder.Entity("Domain.RefreshTokens.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<DateTime>("ExpiredDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_date")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("jwt_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Domain.Comments.Comment", b =>
                {
                    b.HasOne("Domain.Problems.Problem", "Problem")
                        .WithMany("Comments")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_problems_problem_id");

                    b.HasOne("Domain.Identity.Users.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_user_id");

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Identity.Users.User", b =>
                {
                    b.HasOne("Domain.Identity.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Identity.Users.UserImage", b =>
                {
                    b.HasOne("Domain.Identity.Users.User", "User")
                        .WithOne("UserImage")
                        .HasForeignKey("Domain.Identity.Users.UserImage", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_images_users_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Problems.CoordinatorImage", b =>
                {
                    b.HasOne("Domain.Problems.Problem", "Problem")
                        .WithMany("CoordinatorImages")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_coordinator_images_id");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("Domain.Problems.Problem", b =>
                {
                    b.HasOne("Domain.Identity.Users.User", "Coordinator")
                        .WithMany()
                        .HasForeignKey("CoordinatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_problems_users_coordinator_id");

                    b.HasOne("Domain.Identity.Users.User", "CreatedBy")
                        .WithMany("Problems")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_problems_users_created_by_id");

                    b.Navigation("Coordinator");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Domain.Problems.ProblemImage", b =>
                {
                    b.HasOne("Domain.Problems.Problem", "Problem")
                        .WithMany("Images")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_images_id");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("Domain.Ratings.Rating", b =>
                {
                    b.HasOne("Domain.Problems.Problem", "Problem")
                        .WithMany("Ratings")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ratings_problems_problem_id");

                    b.HasOne("Domain.Identity.Users.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ratings_users_user_id");

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.RefreshTokens.RefreshToken", b =>
                {
                    b.HasOne("Domain.Identity.Users.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Identity.Users.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Problems");

                    b.Navigation("Ratings");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserImage");
                });

            modelBuilder.Entity("Domain.Problems.Problem", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("CoordinatorImages");

                    b.Navigation("Images");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
